[package]
name = "plix"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.15.0", features = ["derive"] }
chrono = "0.4.38"
eframe = { version = "0.27.2", features = ["wayland", "wgpu"] }
flume = "0.11.0"
image = "0.25.1"
notify = "6.1.1"
pollster = "0.3.0"
